projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4000
  prisma:
    schemaPath: src/hello-world/generated/prisma.graphql
    extensions:
      prisma: hello-world/prisma.yml
  hooks:
    post-deploy:
      - graphql get-schema -p hello-world